name: 程式碼編寫指南，由 @mdo 撰寫
description: 一致、有彈性且能長期維護的 HTML、CSS 開發標準。
url: https://codeguide.intersection.tw
permalink: pretty
sass:
  style: compressed
version: 4.0.0
og_image: https://codeguide.intersection.tw/code-guide-social.png
